import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import Navbar from "../../components/Navbar";

// Load the Inter font
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap", // Ensures the font swaps quickly for better performance
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} font-sans antialiased`}>
                {" "}
                <Navbar />
                {children}
            </body>
        </html>
    );
}
